### ISSUE TITLE
black_box in the wrong place i think?

### ISSUE THREAD

**Issue by c00t** [byronwasti/async-fn-pointer-perf#1]
Hi,
I just read through your post. it discusses the overhead of making synchronous or asynchronous function calls in Rust in various ways, right? Here are some questions that come to my mind

LLVM is smart enough to eliminate simple function calls altogether, but this is not the general case for test frameworks. here are links to godbolt:
- [function-pointer.rs](https://godbolt.org/z/89nzcb4vq)
- [boxed-function-pointer.rs](https://godbolt.org/z/Y53rd19vn)

they are doing the same thing, +2 then compare to 500000000. the measured time does not contain a function call instruction, i.e. `call` or `jmp`. I think it's a result of `black_box` being used in the wrong place.

I made a modification that I didn't scrutinize its assembly output, but it's assembly code contains an alloc call for `Box::new(foo)`(make sure pointer are put to heap) as well as a `call foo` instruction.

```rust
use std::hint::black_box;

pub fn main() {
    load_test(black_box(Box::new(foo)));
}

fn load_test(func: Box<fn(i32) -> i32>) {
    for i in 0..250_000_000 {
        let _x = func(i);;
    }
}

fn foo(arg: i32) -> i32 {
    black_box(arg * 2)
}
```

Although I'd like to see IR representations of other async-func-pointer strategies as well, the compilation results of the asynchronous code are too complicated... If I have more time...

**Comment by byronwasti** [comment]
Oh shoot, you're totally right. Thanks for pointing this out! When digging into this issue I just looked at the IR for the async-func-pointer and similarly found them too complicated, and I totally missed checking the normal function pointers (which is really silly in hindsight).

I'll update the repo & post with the actual timings. Thanks again!

**Comment by byronwasti** [comment]
Code updated, new measurements taken, and post updated (with attribution for the fix -- please let me know if its not satisfactory!)

I'll hopefully carve out some time to investigate the async case some more as well. Thanks!
